### ISSUE TITLE
Class not found laravel 5.2

### ISSUE THREAD

**Issue by randinfo** [Askedio/Laravel-100-Page-Speed#1]
php artisan clear-compiled

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Askedio\Laravel100PageSpeed\PageSpeedServiceProvider' not found

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:

**Comment by gcphost** [comment]
Hi

Thank you. It seems there were a few issues porting over to a Package.

I have resolved the issues and tested locally.
